"""Fully hand-written calls, already in Whisper style (no extra noise is applied).

They cover the hardest cases the templates do not: scams that never say "money", calls that only
*talk about* scams, mixed Polish/English, and a few unusual patterns.
Format: (id_suffix, lang, label, scam_type, difficulty, [(speaker, text), ...]).
"""

from common import C, S

CALLS = [
    # ------------------------------------------------------------------------------- Polish scams
    ("pl_scam_01", "pl", "scam", "police", "hard", [
        (C, "dzień dobry, nadkomisarz Wojciech Rak, wydział kryminalny"),
        (S, "dzień dobry, słucham"),
        (C, "czy pani jest sama w domu? pytam bo sprawa jest delikatna"),
        (S, "sama, mąż jest w sanatorium"),
        (C, "dobrze. od tygodnia obserwujemy grupę która okrada starsze osoby w pani okolicy, pani adres był na ich liście"),
        (S, "o matko, co ja mam zrobić"),
        (C, "nic na razie, proszę zachować spokój. zadzwonię jutro rano i powiem jak może nam pani pomóc w zatrzymaniu"),
        (C, "proszę nikomu nie mówić o tej rozmowie, nawet córce, oni mogą mieć kogoś w rodzinie albo w banku"),
        (S, "dobrze, nie powiem"),
        (C, "i proszę sprawdzić ile ma pani w domu oszczędności, jutro to zabezpieczymy"),
    ]),
    ("pl_scam_02", "pl", "scam", "investment", "hard", [
        (C, "hello dzień dobry, mówi Kevin, jestem pana account manager z platformy trading"),
        (S, "kto? nie rozumiem"),
        (C, "account manager, opiekun konta. zarejestrował się pan u nas przez internet, na reklamie z tym znanym aktorem"),
        (S, "a, coś klikałem na facebooku"),
        (C, "exactly, no więc ma pan już konto, tylko trzeba zrobić pierwszy deposit, 250 dolarów, to jest około 1000 zł"),
        (C, "nasz system AI robi trading automatycznie, profit jest około 8 procent dziennie, really"),
        (S, "a jak mam to zapłacić?"),
        (C, "zainstaluje pan anydesk, ja pomogę, to jest very easy, i podamy kartę"),
        (S, "córka mówi żebym nie instalował nic"),
        (C, "córka nie musi wiedzieć, zrobi pan jej niespodziankę jak będą zyski"),
    ]),
    ("pl_scam_03", "pl", "scam", "grandchild", "hard", [
        (C, "babciu cześć to ja Kasia"),
        (S, "kasiu? jak dobrze cię słyszeć, gdzie ty jesteś"),
        (C, "jestem na wymianie w hiszpanii pamiętasz, dzwonię przez internet dlatego tak trzeszczy"),
        (S, "a no tak mama mówiła"),
        (C, "babciu, ukradli mi plecak z dokumentami i kartą, jestem na komisariacie"),
        (S, "jezus maria a nic ci nie jest"),
        (C, "nic, tylko nie mam za co wrócić do hostelu. mogłabyś kupić w żabce taką kartę paysafe i przeczytać mi kod"),
        (S, "a ile"),
        (C, "na 500 zł, dwie karty po 250, pani w sklepie będzie wiedziała"),
        (C, "nie dzwoń do mamy bo ona ma teraz egzamin w pracy i się zdenerwuje, sama jej powiem"),
    ]),
    ("pl_scam_04", "pl", "scam", "bank", "hard", [
        (C, "dzień dobry, Monika Zawada, departament bezpieczeństwa, dzwonię w sprawie zgłoszenia kredytu"),
        (S, "jakiego kredytu, ja nie brałem kredytu"),
        (C, "właśnie, wpłynął wniosek na 38 tysięcy na pana dane, został złożony przez internet"),
        (S, "ale to nie ja"),
        (C, "wiem, dlatego dzwonię. przełączę pana do policji, proszę się nie rozłączać"),
        (C, "dzień dobry, aspirant Kubiak, potwierdzam, prowadzimy sprawę, w pana oddziale pracuje osoba która wyłudza kredyty"),
        (C, "żeby zablokować kredyt, musi pan zaciągnąć kredyt lustrzany i wpłacić środki na rachunek zastrzeżony, wtedy tamten się anuluje"),
        (S, "kredyt lustrzany? pierwszy raz słyszę"),
        (C, "to procedura bankowa, w oddziale proszę powiedzieć że na remont, bo pracownik jest podejrzany"),
    ]),
    ("pl_scam_05", "pl", "scam", "other", "hard", [
        (C, "dzień dobry, kancelaria notarialna z poznania, aplikant Michał Szewc, czy rozmawiam z panem Jerzym"),
        (S, "tak, słucham"),
        (C, "prowadzimy postępowanie spadkowe po zmarłym w kanadzie panu Edwardzie, jest pan jedynym spadkobiercą"),
        (S, "edward? mój wujek wyjechał kiedyś do kanady, ale nie wiedziałem że zmarł"),
        (C, "przykro mi. spadek to około 400 tysięcy dolarów, nieruchomość i oszczędności"),
        (S, "ojej, to niesamowite"),
        (C, "żeby otworzyć postępowanie w polsce, trzeba uiścić opłatę sądową i notarialną, łącznie 6800 zł"),
        (C, "termin mija w piątek, potem sprawa przepada na rzecz skarbu państwa kanady"),
        (S, "a mogę przyjechać do kancelarii"),
        (C, "nie ma potrzeby, wystarczy przelew, wyślę numer sms-em"),
    ]),
    ("pl_scam_06", "pl", "scam", "other", "easy", [
        (C, "dzień dobry, fundacja pomocy dzieciom, zbieramy na operację serca dla 3 letniego Antosia"),
        (S, "oj biedne dziecko"),
        (C, "operacja w stanach kosztuje milion, brakuje jeszcze 40 tysięcy, każda złotówka się liczy"),
        (C, "może pani wesprzeć teraz kodem blik, wystarczy podać mi 6 cyfr z aplikacji"),
        (S, "a ile trzeba dać"),
        (C, "większość osób daje 300 zł, ale może pani więcej, proszę szybko bo zbiórka kończy się dzisiaj o 20"),
        (S, "nie wiem jak zrobić blika"),
        (C, "pomogę pani, proszę otworzyć aplikację banku, nie rozłączamy się"),
    ]),
    ("pl_scam_07", "pl", "scam", "other", "hard", [
        (C, "dzień dobry, zakład ubezpieczeń społecznych, oddział w krakowie, dzwonię w sprawie waloryzacji"),
        (S, "dzień dobry, coś nie tak z emeryturą?"),
        (C, "nie, wszystko dobrze, w tym roku przysługuje pani wyrównanie, tylko trzeba zaktualizować dane w systemie"),
        (S, "a co trzeba zrobić"),
        (C, "zaraz przyjdzie sms z linkiem, proszę wejść i zalogować się tak jak do banku"),
        (S, "do banku? a po co bank"),
        (C, "żeby wyrównanie trafiło na właściwy rachunek, to jest weryfikacja tożsamości, profil zaufany"),
        (C, "a potem proszę mi przeczytać kod który przyjdzie drugim smsem, to potwierdza wniosek"),
    ]),
    ("pl_scam_08", "pl", "scam", "grandchild", "hard", [
        (C, "dziadku, to ja, bartek, mam ogromną prośbę"),
        (S, "bartuś? co się dzieje"),
        (C, "nie mogę teraz długo gadać, jestem u notariusza, kupujemy z ewą mieszkanie i zabrakło nam na umowę"),
        (S, "to wspaniale że mieszkanie"),
        (C, "no tylko notariusz nie poczeka, za pół godziny podjedzie do ciebie mój kolega marcin"),
        (C, "daj mu to co trzymasz w szafie w tej kopercie, oddam ci w przyszłym tygodniu jak bank wypłaci"),
        (S, "całą kopertę?"),
        (C, "tak, i nie dzwoń teraz do mamy, chcemy im zrobić niespodziankę z tym mieszkaniem"),
    ]),
    # ----------------------------------------------------------------------------- Polish normal
    ("pl_normal_01", "pl", "normal", "none", "hard", [
        (C, "mamo, tylko się nie denerwuj, jestem w szpitalu"),
        (S, "jezus maria, co się stało"),
        (C, "spadłem z roweru, mam złamaną rękę, już jest w gipsie, nic poważnego"),
        (S, "boże, a w którym szpitalu"),
        (C, "na prokocimiu. mogłabyś przywieźć mi piżamę i ładowarkę do telefonu? zostaję do jutra na obserwacji"),
        (S, "pewnie, zaraz przyjadę, coś jeszcze"),
        (C, "dowód osobisty mam, tylko szczoteczkę do zębów. i nie mów jeszcze tacie, on ma ważne spotkanie, sam mu zadzwonię wieczorem"),
        (S, "dobrze, dobrze, będę za godzinę"),
    ]),
    ("pl_normal_02", "pl", "normal", "none", "hard", [
        (C, "dzień dobry, kancelaria notarialna przy ulicy długiej, dzwonię potwierdzić termin w sprawie testamentu"),
        (S, "tak, umawiałam się w zeszłym tygodniu"),
        (C, "czwartek o 11, proszę zabrać dowód osobisty i akt własności mieszkania"),
        (S, "a ile kosztuje taki testament"),
        (C, "taksa notarialna to 50 zł plus vat, płatne na miejscu, kartą albo gotówką"),
        (S, "dobrze, przyjdę z synem"),
        (C, "oczywiście, do zobaczenia w czwartek"),
    ]),
    ("pl_normal_03", "pl", "normal", "none", "hard", [
        (C, "cześć mamo, słuchaj, mam do ciebie prośbę"),
        (S, "cześć córciu, mów"),
        (C, "zosia musi mieć leczenie kanałowe, dentysta prywatnie chce 2000 zł, a my w tym miesiącu po remoncie"),
        (S, "oj, to dużo"),
        (C, "wiem, mogłabyś nam przelać 1000? oddamy w dwóch ratach, piotrek już o tym wie i się zgadza"),
        (S, "dobrze, przeleję wam jutro, to samo konto?"),
        (C, "tak, to samo, dziękuję mamo, wpadniemy w niedzielę z zosią"),
        (S, "to zrobię pierogi"),
    ]),
    ("pl_normal_04", "pl", "normal", "none", "easy", [
        (C, "dzień dobry, przychodnia na osiedlu, dzwonimy w sprawie szczepienia przeciw grypie"),
        (S, "dzień dobry, a już są szczepionki?"),
        (C, "tak, dla seniorów po 65 roku życia bezpłatne, może pan przyjść w każdy wtorek i czwartek od 8 do 12"),
        (S, "a trzeba się zapisać?"),
        (C, "nie trzeba, wystarczy przyjść z dowodem"),
        (S, "dobrze, dziękuję za telefon"),
    ]),
    ("pl_normal_05", "pl", "normal", "none", "hard", [
        (C, "hej babciu, sorry że dzwonię tak późno, mam teraz deadline na uczelni"),
        (S, "nic nie szkodzi kochanie, jak tam w londynie"),
        (C, "spoko, trochę stressful, mam exam w piątek, ale ogarniam"),
        (S, "a jesz coś porządnego"),
        (C, "tak tak, gotuję z flatmates, zrobiliśmy nawet pierogi, wyszły takie sobie haha"),
        (S, "to przyjedź na święta to cię nauczę"),
        (C, "przylatuję 20 grudnia, już mam bilet. love you babciu"),
        (S, "ja ciebie też, uważaj na siebie"),
    ]),
    ("pl_normal_06", "pl", "normal", "none", "hard", [
        (C, "dzień dobry, młodszy aspirant Nowicka, dzielnicowa z komisariatu na podgórzu"),
        (S, "dzień dobry, coś się stało?"),
        (C, "nie, nic, zapraszamy seniorów na spotkanie w klubie osiedlowym o oszustwach metodą na wnuczka i na policjanta"),
        (C, "opowiemy jak działają oszuści, że policja nigdy nie prosi o pieniądze ani o przekazanie gotówki, i że nie wolno podawać kodu blik"),
        (S, "a kiedy to spotkanie?"),
        (C, "w środę o 17, wstęp wolny, będzie też ktoś z banku"),
        (S, "przyjdę z sąsiadką, dziękuję"),
    ]),
    ("pl_normal_07", "pl", "normal", "none", "hard", [
        (C, "dzień dobry, bank, dzwonię potwierdzić, że zgodnie z pana wczorajszą dyspozycją w oddziale karta została zastrzeżona"),
        (S, "tak, zgubiłem ją w sklepie"),
        (C, "nowa karta przyjdzie listem poleconym w ciągu 7 dni, pin ustawi pan sam w bankomacie"),
        (S, "a te pieniądze na koncie są bezpieczne?"),
        (C, "tak, konto działa normalnie, tylko stara karta jest zablokowana. nie prosimy pana o żadne dane"),
        (S, "dobrze, dziękuję"),
    ]),
    ("pl_normal_08", "pl", "normal", "none", "hard", [
        (C, "halinka, cześć, musisz to usłyszeć, wczoraj do mnie dzwonili oszuści"),
        (S, "co ty mówisz, jacy oszuści"),
        (C, "ktoś się podawał za policjanta, że niby mój wnuczek miał wypadek i potrzebna kaucja 50 tysięcy"),
        (C, "i żebym nikomu nie mówiła, a pieniądze miał odebrać kurier"),
        (S, "i co zrobiłaś"),
        (C, "rozłączyłam się i zadzwoniłam do tomka, a on siedział w pracy, cały i zdrowy. zgłosiłam to na policję"),
        (S, "dobrze zrobiłaś, ja bym chyba umarła ze strachu"),
        (C, "no właśnie dlatego dzwonię, uważaj na siebie"),
    ]),
    # ------------------------------------------------------------------------------ English scams
    ("en_scam_01", "en", "scam", "grandchild", "hard", [
        (C, "hello, is this Mrs. Taylor? my name is Richard Hayes, I'm an attorney"),
        (S, "yes, this is she"),
        (C, "I'm representing your grandson Michael, he asked me to call you, he's okay, he's not hurt"),
        (S, "oh thank god, what's going on"),
        (C, "he was a passenger in a car that was stopped this morning, and unfortunately there were some substances found"),
        (C, "he's being held, but I spoke with the judge and we can get the charges reduced and his record kept clean"),
        (S, "what does he need"),
        (C, "there's a court bond of 9000 dollars, and Michael is very worried about his parents finding out, he asked that you keep this between the two of you"),
        (C, "a court officer can come by your home this afternoon to collect it"),
    ]),
    ("en_scam_02", "en", "scam", "other", "hard", [
        (C, "hi, this is Jason from the refund department, you had a computer protection subscription with us"),
        (S, "I think so, my son set it up"),
        (C, "we're closing the service and you're owed a refund of 299 dollars"),
        (C, "I'll just need to connect to your computer to process it, please go to the website I give you"),
        (S, "okay, it's open now"),
        (C, "oh no, I made a mistake, I typed 29900 instead of 299, you've received 29900 dollars, this is very bad, I could lose my job"),
        (C, "please, you need to send back the difference, the bank won't do it, you can buy target gift cards and read me the codes"),
        (S, "oh dear, that's a lot of gift cards"),
    ]),
    ("en_scam_03", "en", "scam", "bank", "hard", [
        (C, "good afternoon, this is Emma from Harbor Federal, I'm calling about a payment we've stopped"),
        (S, "a payment?"),
        (C, "yes, someone tried to add a new payee to your account, we've paused it, I just want to make sure you're protected"),
        (C, "we're going to send a one time code to your phone to cancel the request, could you read it back to me when it arrives"),
        (S, "okay, I got a text, it says don't share this code with anyone"),
        (C, "that's right, that's a standard message, it doesn't apply to the bank's own fraud team, go ahead"),
        (S, "it's 4 8 1 9 2 0"),
        (C, "perfect, thank you, I'll stay on the line while the cancellation goes through"),
    ]),
    ("en_scam_04", "en", "scam", "investment", "hard", [
        (C, "hey Dorothy, it's Daniel, from the widowers group online, I hope it's okay I called"),
        (S, "oh Daniel, how nice, I loved your message about your garden"),
        (C, "I've been thinking about you all week. you know, my niece works at a crypto firm and she's been helping me with my retirement"),
        (S, "oh, I don't know anything about crypto"),
        (C, "neither did I, but my account is up 40 percent since june, I can show you the screenshots"),
        (C, "I'd love for you to have that security too. you could start small, maybe 5000, and she'll set everything up"),
        (S, "I'd have to ask my son"),
        (C, "he might not understand, younger people are skeptical, but this is our little secret, okay"),
    ]),
    ("en_scam_05", "en", "scam", "other", "easy", [
        (C, "this is agent Thompson from the internal revenue service, you owe back taxes of 4,872 dollars"),
        (S, "I file my taxes every year"),
        (C, "our records show errors from 2019, if you don't pay today a warrant will be issued and police will come to your house"),
        (C, "you can pay with gift cards or bitcoin at the nearest atm, I'll stay on the line"),
        (S, "can I talk to my accountant first"),
        (C, "no, you must pay immediately and don't hang up, this is your final notice"),
    ]),
    ("en_scam_06", "en", "scam", "bank", "hard", [
        (C, "dzień dobry, hello, this is the security team from your bank, is this Mr. Kowalski"),
        (S, "yes, tak, Kowalski"),
        (C, "we noticed someone in poland tried to log into your account, did you travel recently"),
        (S, "no, no, I am home, w domu"),
        (C, "okay, so your money is at risk, we will move it to a protected account under your name until we finish the investigation"),
        (S, "protected account? I don't understand so good"),
        (C, "it's simple, I'll guide you, please open your banking app now, and please don't call the branch, the line is compromised"),
    ]),
    # ------------------------------------------------------------------------------ English normal
    ("en_normal_01", "en", "normal", "none", "hard", [
        (C, "Margaret, you won't believe what happened to me yesterday, someone tried to scam me"),
        (S, "oh no, what happened"),
        (C, "a man called saying he was my grandson and he was in jail and needed bail money, 5000 dollars in gift cards"),
        (C, "he even said don't tell mom and dad. I hung up and called Tommy and he was at work, totally fine"),
        (S, "good for you, I've heard about those calls"),
        (C, "I reported it to the police, they said it happens every day. so be careful, okay"),
        (S, "I will, thanks for telling me"),
    ]),
    ("en_normal_02", "en", "normal", "none", "hard", [
        (C, "grandma, it's Ben, I'm okay, but I'm at the emergency room"),
        (S, "oh my goodness, what happened"),
        (C, "I fell off my bike and broke my wrist, they're putting a cast on it now"),
        (S, "do you need me to come"),
        (C, "no, mom is on her way, my phone is almost dead, could you just call her and tell her it's the north entrance"),
        (S, "of course, sweetheart, I'll call her right now"),
        (C, "thanks grandma, love you"),
    ]),
    ("en_normal_03", "en", "normal", "none", "hard", [
        (C, "hello, this is officer Reyes, community liaison at the Fairview police department"),
        (S, "oh, hello"),
        (C, "we're holding a free fraud prevention seminar for seniors at the library next tuesday"),
        (C, "we'll explain how scammers pretend to be police or bank employees and ask for gift cards, and why we will never ask you for money"),
        (S, "that sounds useful, what time"),
        (C, "2 pm, coffee and cookies provided"),
        (S, "I'll bring my neighbor"),
    ]),
    ("en_normal_04", "en", "normal", "none", "hard", [
        (C, "hi, this is the pharmacy at Oak Street, your insurance changed your heart medication to a generic"),
        (S, "is it the same medicine"),
        (C, "yes, same active ingredient, the copay is 45 dollars now instead of 10, I'm sorry about that"),
        (S, "that's a lot more"),
        (C, "you can ask your doctor about a patient assistance program, or I can check with your insurance tomorrow"),
        (S, "please do, thank you"),
    ]),
    ("en_normal_05", "en", "normal", "none", "hard", [
        (C, "hi mom, it's Sarah, quick question"),
        (S, "hi honey"),
        (C, "the transmission on my car died, the shop wants 1500 dollars. could you wire me the money? I'll pay you back when my bonus comes in march"),
        (S, "of course, is the account still the same"),
        (C, "yes, same one. Dave says thank you too, we'll bring the kids over on easter"),
        (S, "I'll do it this afternoon"),
    ]),
    ("en_normal_06", "en", "normal", "none", "easy", [
        (C, "hello, this is Janet from the community blood drive, you donated with us last spring"),
        (S, "oh yes, I remember"),
        (C, "we're having another drive at the church on the 14th, would you like to sign up for a time"),
        (S, "sure, morning is better for me"),
        (C, "I'll put you down for 10 am, please eat a good breakfast"),
        (S, "will do, thank you"),
    ]),
]
