"""Pre-recorded voice prompts (8 kHz mu-law files generated by scripts/make_prompts.sh).

Files: `DATA_DIR/prompts/<name>_<lang>.ulaw` (raw G.711 mu-law, 8 kHz, mono). They are not
committed (Apple voice licensing); when a file is missing the bridge falls back to a beep
tone and this module logs it once per prompt.
"""

from __future__ import annotations

import logging
from functools import cache
from pathlib import Path

from app.audio.convert import APP_FRAME_BYTES, PHONE_FRAME_BYTES, Framer, float32_to_pcm16le
from app.audio.g711 import mulaw_decode, to_float32
from app.audio.resample import STT_RATE, TWILIO_RATE, resample
from app.config import Lang
from app.logging_setup import log_event
from app.prompts import VOICE_PROMPTS

logger = logging.getLogger(__name__)

MAX_PROMPT_BYTES = 8000 * 30  # 30 s


class PromptLibrary:
    def __init__(self, directory: Path | str) -> None:
        self.directory = Path(directory)
        self._missing_logged: set[tuple[str, str]] = set()
        # Cache per instance (cache on a method would keep instances alive).
        self._phone = cache(self._load_phone)
        self._app = cache(self._load_app)

    def _path(self, name: str, lang: Lang) -> Path:
        if name not in VOICE_PROMPTS or lang not in ("pl", "en"):
            raise ValueError(f"unknown prompt {name}/{lang}")
        return self.directory / f"{name}_{lang}.ulaw"

    def _read(self, name: str, lang: Lang) -> bytes | None:
        path = self._path(name, lang)
        try:
            size = path.stat().st_size
            if size == 0 or size > MAX_PROMPT_BYTES:
                raise ValueError(f"bad size {size}")
            return path.read_bytes()
        except (OSError, ValueError) as exc:
            if (name, lang) not in self._missing_logged:
                self._missing_logged.add((name, lang))
                log_event(
                    logger,
                    logging.WARNING,
                    "voice_prompt_missing",
                    prompt=name,
                    lang=lang,
                    error=type(exc).__name__,
                    fallback="tone",
                )
            return None

    def _load_phone(self, name: str, lang: Lang) -> tuple[bytes, ...] | None:
        data = self._read(name, lang)
        if data is None:
            return None
        return tuple(
            data[i : i + PHONE_FRAME_BYTES] for i in range(0, len(data), PHONE_FRAME_BYTES)
        )

    def _load_app(self, name: str, lang: Lang) -> tuple[bytes, ...] | None:
        data = self._read(name, lang)
        if data is None:
            return None
        audio16k = resample(to_float32(mulaw_decode(data)), TWILIO_RATE, STT_RATE)
        return tuple(Framer(APP_FRAME_BYTES).push(float32_to_pcm16le(audio16k)))

    def phone_frames(self, name: str, lang: Lang) -> tuple[bytes, ...] | None:
        """20 ms mu-law 8 kHz frames for the caller, or None if the file is missing."""
        return self._phone(name, lang)

    def app_frames(self, name: str, lang: Lang) -> tuple[bytes, ...] | None:
        """20 ms PCM16 LE 16 kHz frames for the senior's app, or None if missing."""
        return self._app(name, lang)

    def status(self) -> dict[str, bool]:
        return {
            f"{name}_{lang}": self._path(name, lang).is_file()
            for name in VOICE_PROMPTS
            for lang in ("pl", "en")
        }
